### ISSUE TITLE
channel_enabled appears to index ChannelMask incorrectly

### ISSUE THREAD

**Issue by bldh** [ivajloip/rust-lorawan#91]
Hi,

I have been having a look at implementing LinkADRReq for AU915 and have noticed that the channel_enabled appears to index the ChannelMask incorrectly. 

LoRaMAC-node stores channel masks directly from the LinkADRReq MAC command and when setting the 1st sub band using a ChMaskCtrl of 5 they write to the right most bits of the ChannelMask. [Link to example.](https://github.com/Lora-net/LoRaMac-node/blob/e851b079c82ba1bcf3f4d291ab69a571b0bf458a/src/mac/region/RegionAU915.c#L618)

Currently channel_enabled indexes as though index 0 stores the lowest channels of the mask.

I have implemented a potential fix for this [here](https://github.com/bldh/rust-lorawan/commit/e93296807cd81703e0ae0cbcdb09d97531f426bf)

**Comment by lthiery** [comment]
@bldh thanks for bringing up the topic.

However, I think that your fix is not quite right. From the 1.0.4 specification,
```
The channel mask control ( ChMaskCntl ) field controls the interpretation of the previously defined ChMask bit mask. It controls the block of 16 channels to which the ChMask applies. It can also be used to turn all channels on or off globally using a specific modulation. The meaning of ChMaskCntl is region-specific and defined in the “LoRaWAN Regional Parameters” [RP002] document.
```

This tells me that we need to hook into region handlers with the ChMaskCntl field (contained in the Redundancy byte) rather than makes changes to the global ChannelMask encoding functions. Glancing at the regional specification, it seems the current code is correct for "Dynamic Channel Plans" (eg: EU868 or AS923) but "Dynamic Channel Plans" (eg: US915 and AU915) need special handling of the ChMaskCntl field when parsing the ChannelMask in LinkADR.
