### ISSUE TITLE
Out of range panic while decoding packet

### ISSUE THREAD

**Issue by CBJamo** [ivajloip/rust-lorawan#94]
```
thread 'main' panicked at 'range end index 13 out of range for slice of length 12', /home/cbjamo/.cargo/git/checkouts/rust-lorawan-d3dc04aa7aafaad5/956bde4/encoding/src/parser.rs:565:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
 I had some debug logging running at the time, but unfortunately not RUST_BACKTRACE. Note that I'm a little behind the latest git, so the error is on line [parser.rs#L566](https://github.com/ivajloip/rust-lorawan/blob/master/encoding/src/parser.rs#L566) in the current source.

I believe the core issue is that when the device is parsing a packet (See [async](https://github.com/ivajloip/rust-lorawan/blob/master/device/src/async_device/mod.rs#L239) and [state machine](https://github.com/ivajloip/rust-lorawan/blob/master/device/src/state_machines/session.rs#L438)) to get the frame count to pass to the validate_mic function. We pass through the DataHeader trait's .fhdr() function, which, via the fhdr_length function, assumes the length field in the header is good.

So I got a bad downlink here, pulled some garbage out of the packet, and indexed out of bounds. I'm not sure what the cleanest way to fix this is. My gut says make the validate_mic function find the frame count on it's own, rather than passing through the trait's functions.

**Comment by ivajloip** [comment]
Hi Caleb,

Thank you for filing thist and apologies for the delay! Looking at the code, the issue that you were seeing seems to come from [here](https://github.com/ivajloip/rust-lorawan/blob/eeba79317f0a146075e2fc669ccba18cb4215fa7/encoding/src/parser.rs#L566), with the actual issue being in [this TODO](https://github.com/ivajloip/rust-lorawan/blob/eeba79317f0a146075e2fc669ccba18cb4215fa7/encoding/src/parser.rs#L639) - we should compute a better value. So the issue is that if `fhdr_length == data.len()` and that is at least 12, we will try to index with non-existing element. In reality we always need 5 + fhdr_length of bytes to have a valid packet in any case, so I am going to update the code accordingly.
